spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name:
      tracks-svc
  datasource:
    url: jdbc:postgresql://tracks_postgres:5433/tracks_db?currentSchema=public
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: image_broker
    password: guest
    username: guest
    port: 5672
    virtual-host: /

minio:
  bucket: audio
  url: audio_minio:9002
  accessKey: admin
  secretKey: adminadmin
ffmpeg:
  path: /usr/bin/ffmpeg
logging:
  level:
    web: trace
