spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name:
      player-service
  datasource:
    url: jdbc:postgresql://localhost:5436/player_db?currentSchema=public
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
minio:
  bucket: audio
  url: http://localhost:9002
  accessKey: admin
  secretKey: adminadmin

logging:
  level:
    web: trace
server:
  port: 4444