services:
  user_db:
    image: postgres:13.3
    container_name: auth_postgres
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      PG_DATA: "/var/lib/postgresql/data/pg_data"
    ports:
      - "5432:5432"
    volumes:
      - userdb-data:/var/lib/postgresql/data
      - ./user-service/migrations/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${AUTH_POSTGRES_USER} -d ${AUTH_POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "4G"
    networks:
      auth:

  nginx:
    image: nginx:1.27
    container_name: api_gateway
    ports:
      - "8080:80"
    volumes:
      - ./api-gateway/build/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
     test: ["CMD-SHELL", "curl -f http://localhost/health"]
     interval: 10s
     timeout: 5s
     retries: 3
     start_period: 15s
    depends_on:
      auth_service:
        condition: service_started
      image_service:
        condition: service_started
      track_service:
        condition: service_started
    restart: unless-stopped
    networks:
      auth:
      image:
      audio:
      bus:
      search:

  redis:
    image: redis:7.4.2
    container_name: auth_redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    volumes:
      - authcache-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    networks:
      auth:

  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: image_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"
    networks:
      auth:
      image:
      audio:

  auth_service :
    build: ./user-service
    image: auth_backend:latest
    container_name: auth_backend
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      user_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      auth:
      bus:

  image_service:
    build: ./image-service
    image: image_backend:latest
    container_name: image_backend
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      auth_service:
        condition: service_started
    networks:
      image:

  track_db:
    image: postgres:13.3
    container_name: tracks_postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=tracks_db
    volumes:
      - trackdb-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      audio:

  player_db:
    image: postgres:13.3
    container_name: player_postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=player_db
    volumes:
      - playerdb-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      player:

  search_service:
    build: ./search-service
    image: search_backend:latest
    container_name: search_backend
    restart: unless-stopped
    ports:
      - "8084:8084"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      bus:
      search:

  track_service:
    build: ./tracks-service
    image: audio_backend:latest
    container_name: track_backend
    restart: unless-stopped
    ports:
      - "8083:8080"
    depends_on:
      track_db:
        condition: service_started
      minio1:
        condition: service_started
      image_service:
        condition: service_started
      search_service:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://tracks_postgres:5432/tracks_db"
      JAVA_OPTS: "-Xmx512m"
      MINIO_BUCKET: "audio"
      MINIO_URL: "http://minio1:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "adminadmin"
      LOGGING_LEVEL_WEB: "trace"
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
    networks:
      audio:
      bus:
      search:

  player_service:
    build: ./player-service
    image: player_backend:latest
    container_name: player_backend
    restart: unless-stopped
    ports:
      - "8085:8080"
    depends_on:
      player_db:
        condition: service_started
      minio1:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://player_postgres:5432/player_db"
      JAVA_OPTS: "-Xmx512m"
      MINIO_BUCKET: "audio"
      MINIO_URL: "http://minio1:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "adminadmin"
      LOGGING_LEVEL_WEB: "trace"
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
    networks:
      player:

  minio:
    image: minio/minio
    container_name: image_minio
    command: minio server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - image-minio-data:/data
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --show-error --fail http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "4G"
    networks:
      image:

  minio1:
    image: minio/minio:latest
    container_name: minio1
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    command: minio server --console-address ":9003" /data
    restart: unless-stopped
    ports:
      - "9002:9000"
      - "9003:9003"
    volumes:
      - audio-minio-data:/data
    networks:
      audio:
      player:

  zoo:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zoo
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      bus:

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD-SHELL", "nc -z kafka 29092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      zoo:
        condition: service_started
    networks:
      bus:

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8091:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zoo:2181
    depends_on:
      kafka:
        condition: service_started
    networks:
      bus:

  node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: node01
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - search-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - search

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://node01:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      node01:
        condition: service_started
    networks:
      - search

volumes:
  userdb-data:
  trackdb-data:
  playerdb-data:
  image-minio-data:
  audio-minio-data:
  authcache-data:
  rabbitmq-data:
  search-data:

networks:
  auth:
    driver: bridge
  image:
    driver: bridge
  audio:
    driver: bridge
  search:
    driver: bridge
  bus:
    driver: bridge
  player:
    driver: bridge