version: '3.1'

volumes:
  pg_tracks:
  minio-audio:
    driver: local

services:
  tracks_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=tracks_db
    volumes:
      - pg_tracks:/var/lib/postgresql/data

    ports:
      - "127.0.0.1:5432:5432"

  track_svc:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - tracks_db
      - minio
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://tracks_db:5432/tracks_db"
      JAVA_OPTS: "-Xmx512m"
      MINIO_BUCKED: "audio"
      MINIO_URL: "http://minio:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "adminadmin"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    command: server ~/minio --console-address :9090
    ports:
      - "9090:9090"
      - "9000:9000"
    volumes:
      - minio-audio:/minio
