http:
  port: 8081
  write_timeout: 5s
  read_timeout: 5s
  shutdown_timeout: 10s
minio:
  connection:
    port: 9000
    host: minio
    access_key_id: minioadmin
    use_ssl: false
  buckets:
    profile_bucket: profile
    track_bucket: track
    playlist_bucket: playlist
rabbitmq:
  connection:
    port: 5672
    host: image_broker
    username: guest
  publishers:
    profile_image_publisher:
      exchange: image
      routing_key: profile
    playlist_image_publisher:
      exchange: image
      routing_key: playlist
    track_image_publisher:
      exchange: image
      routing_key: track