http:
  port: 8082
  write_timeout: 5s
  read_timeout: 5s
  shutdown_timeout: 10s
postgres:
  port: 5432
  host: localhost
  username: postgres
  db_name: user_db
  ssl_mode: disable
token:
  access_ttl: 1h
  refresh_ttl: 48h
rabbitmq:
  connection:
    port: 5672
    host: localhost
    username: guest
  image_binding:
    queue_name: profile_image
    exchange_kind: direct
    exchange_name: image
    routing_key: profile
    concurrency: 10
    consumer_tag: image-consumer
redis:
  port: 6379
  host: localhost
  username: redis
  db: 0